cj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views
from . import test
app_name = 'polls'
urlpatterns = [
    path('<int:question_id>/', views.index, name='index'),

    path('<int:question_id>/drawn', test.drawn, name='drawsn'),
    path('vote', views.vote, name='vote'),
    path('esc', test.rank2, name='drawn'),
    path('esr', views.rank1, name='rank'),

]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
class Questionaire(models.Model):
    questionaire_text = models.CharField('问卷名称',max_length=200)
    questionaire_ad = models.TextField('问卷简介',default='')
    pub_date = models.DateTimeField('开始时间',default=timezone.now,)
    end_time = models.DateTimeField('结束时间',default=timezone.now()+datetime.timedelta(days=10))
    questionaire_uid= models.BigIntegerField('序号',default=0)
    drawnd = models.BooleanField(default=False, help_text='是否抽过奖')
    class Meta:
        verbose_name = "Questionaire"
        verbose_name_plural = "试卷"
    def __str__(self):
        return self.questionaire_text
class Question(models.Model):
    questionaire = models.ForeignKey(Questionaire, on_delete=models.CASCADE,help_text='问题所在问卷')
    pub_date = models.DateTimeField('问题创建时间' ,default=timezone.now())
    question_text = models.CharField('问题内容',max_length=200,help_text='问题内容')
    number= models.IntegerField(default=0)
    sf = models.BooleanField('是否多选',default=False)
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "问题"
    def __str__(self):
        return self.question_text
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('答案内容',max_length=200,help_text='需要加上选项字母，如"A.答案内容"')
    votes = models.IntegerField('答案分数',default=0,help_text='正确为一分，多选题非正确选项为-5分')
    answer = models.BooleanField(default = False)
    class Meta:
        verbose_name = "Choice"
        verbose_name_plural = "选项"
    def __str__(self):
        return self.choice_text
class answer(models.Model):
    questionaire = models.ForeignKey(Questionaire,on_delete=models.CASCADE)
    answer_name = models.CharField('答题人姓名',max_length=200)
    answer_choice = models.CharField('答题人的答案',max_length=200,default='')
    answer_email = models.EmailField('答案人人数',default=0)
    answer_number = models.IntegerField('答题人分数',default=0)
    answer_phonenumber=models.BigIntegerField('答案人电话号码',default=0)
    #是否中奖 = models.BooleanField(default=False)
    drawn = models.BooleanField('是否中奖',default=False)
    answer_drawn = models.CharField('奖品',max_length=200, default='未中奖')
    class Meta:
        verbose_name = "answer"
        verbose_name_plural = "回答者"
    def __str__(self):
        return self.answer_name

class think(models.Model):
    think_text = models.CharField('抽奖方案名称',max_length=200,)
    votes = models.IntegerField('抽奖方案序号',default=0,)
    class Meta:
        verbose_name = "think"
        verbose_name_plural = "抽奖方案"
    def __str__(self):
        return self.think_text
class gt(models.Model):
    think = models.ForeignKey(think,on_delete=models.CASCADE)
    name = models.CharField('奖品名称',max_length=200,)
    num = models.IntegerField('获奖人数',default=0,)
    votes = models.IntegerField('获奖最低分数', default=0,help_text='优先从分数高的抽取')
    class Meta:
        verbose_name = "gt"
        verbose_name_plural = "奖品"
    def __str__(self):
        return self.name

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from polls.models import *
from django.utils import timezone
import random
import datetime
import numpy as np

def index(request,question_id):
    z=question_id
    if timezone.now()<Questionaire.objects.filter(id=question_id)[0].pub_date:
        return HttpResponse('还没开始')
    if timezone.now()>Questionaire.objects.filter(id=question_id)[0].end_time:
        return HttpResponse('已经结束')
    f=Questionaire.objects.filter(id=question_id)[0]
    latest_question_list = f.question_set.all().order_by('pub_date')[:5]
    t1 = datetime.datetime.strftime(f.pub_date, '%Y年-%m月-%d日 %H:%M:%S')
    t2 = datetime.datetime.strftime(f.end_time, '%Y年-%m月-%d日 %H:%M:%S')
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
        'f':f,
        't1':t1,
        't2':t2,
        'z' :z,
    }
    return HttpResponse(template.render(context, request))

def vote(request):
    aire=request.POST.get('wjid',1)
    name1 = Questionaire.objects.filter(id=int(aire))[0].question_set.all().order_by('pub_date')[:5]
    f = request.POST['phone_number']
    if Questionaire.objects.get(id=aire).answer_set.filter(answer_phonenumber=f):
        return HttpResponse('抱歉，您已经答过题了')
    s=''
    q=1
    num=0
    for i in name1:
        s=s+' '+str(q)+'.'
        q=q+1

        if i.sf==True:
            r=0
            for j in i.choice_set.all():
                if (request.POST.get('r'+str(j.id),1)!=1) :
                    s = s + j.choice_text[0]
                    if Choice.objects.filter(id=int(request.POST['r'+str(j.id)]))[0].answer==True:
                        r=r+2
            if r < 0:
                r = 0
            if r < len(i.choice_set.all()):
                r = 1
            if r == len(i.choice_set.all()):
                r = 2
            num=num+r
        else:
            if (request.POST.get('r'+str(i.id), 1) != 1):
                s = s + Choice.objects.get(id=int(request.POST['r' + str(i.id)])).choice_text[0]
                if Choice.objects.get(id=int(request.POST['r' + str(i.id)])).answer==True:
                    num = num + 2

    q = answer(questionaire_id=aire, answer_name=request.POST['firstname'], answer_email=request.POST['email'], answer_number=num, answer_choice=s, answer_phonenumber=f )
    q.save()

    return HttpResponse('感谢您的参与')

def rank1(request):
    a=int(request.POST['j1'])
    b=request.POST['wjid']
    ans=[]
    FA=think.objects.get(votes=a)
    FA1=FA.gt_set.all()
    a = np.array([[0 for i in range(len(FA1))] for i in range(2)])
    i=0
    for j in FA1:
        a[0][i]=j.num
        a[1][i] = j.votes
        i=i+1
    c=a[1]
    a=a[0]
    for i in b:
        j=Questionaire.objects.get(id=int(i))
        ranki = j.answer_set.all().filter(answer_number__gte=FA1[len(FA1)-1].votes).order_by('answer_number')
        if len(ranki)<sum(a):
            return HttpResponse(j.questionaire_text+'抽奖人数不足')
        if j.drawnd==True:
            return HttpResponse(j.questionaire_text + '抽过奖了')
        if timezone.now() < j.pub_date:
            return HttpResponse('还没开始')
        if timezone.now() > j.end_time:
            return HttpResponse('已经结束')
        R = np.array([i.answer_number for i in ranki])
        r=[i for i in range(len(ranki))]
        p=0
        for i in c:
            S=np.where(R >= i)[0]
            random.shuffle(S)
            S=S[:a[p]]
            for l in S:
                R[l]=0
                ranki[r[l]].drawn = True
                ranki[r[l]].answer_drawn = FA1[int(p)].name
                ranki[r[l]].save()
            p=p+1
        j.drawnd = True
        j.save()
    for i in b:
        q=Questionaire.objects.get(id=int(i)).answer_set.all().filter(drawn=True).order_by('answer_drawn')
        ans.append(q)
    template = loader.get_template('polls/answer.html')
    context = {
        'ans': ans,
    }
    return HttpResponse(template.render(context, request))

polls/templates/polls/answer.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ f.questionaire_text }}</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
 {% csrf_token %}
    {% for thing in ans %}
    <table class="table table-bordered">
	<caption>中奖人员</caption>
	<thead>
		<tr>
			<th>所属试卷</th>
			<th>姓名</th>
			<th>手机号</th>
            <th>奖品</th>
		</tr>
	</thead>
    <tbody>
        {% for answ in thing %}
        <tr>
			<td>{{ answ.questionaire.questionaire_text }}</td>
			<td>{{ answ.answer_name }}</td>
			<td>{{ answ.answer_phonenumber }}</td>
            <td>{{ answ.answer_drawn }}</td>
		</tr>
        {% endfor %}
	</tbody>
    </table>
    {% endfor %}

polls/templates/polls/cj.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ f.questionaire_text }}</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
 {% csrf_token %}
<form class="bs-example bs-example-form" action="{% url 'polls:rank'%}" method="post">{% csrf_token %}
<div class="form-group" style="padding: 10px 0px 50px;">
        <div class="col-xs-4">
        <label for="exampleInputEmail1">抽奖方案序号</label>
        <input type="number" class="form-control" name="j1" placeholder="抽奖方案序号" required="required">
    </div></div>

<input class="sr-only" type="number" name="wjid" value="{{ b }}" />
     <button type="submit" class="btn btn-default">提交</button>
    </form>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="get">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/drawn.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ f.questionaire_text }}</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
 {% csrf_token %}
 <table class="table table-bordered">
	<caption>获奖名单</caption>
	<thead>
		<tr>
			<th>手机尾号</th>
            <th>奖品</th>
		</tr>
	</thead>
 <tbody>
{% for answer in f %}
　　     <tr>
			<td>{{ answer.answer_phonenumber }}</td>
			<td>{{ answer.answer_drawn }}</td>

		</tr>
        {% endfor %}
 </tbody>
    </table>

polls/templates/polls/dx.html
<p>抱歉您还有题目没有回答，请点击下面链接继续答题：</p>
<p><a href="/polls/{{ aire }}/">有奖答题</a></p>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ f.questionaire_text }}</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
<script>
var cars=new Array();
var i=0;
var j=0;
var k=0;
 {% for ques in latest_question_list %}


     cars[i]={{ ques.id }};
          i=i+1;
      {% if ques.sf %}
            i=i-1;
            cars[i]=-1;
            i=i+1;
            {% for cho in ques.choice_set.all %}
                cars[i]={{ cho.id }}
                i=i+1;
            {% endfor %}
            cars[i]=-2;
            i=i+1;
          {% endif %}


 {% endfor %}

function checkMyform() {
    var f="第";
    var num=0;
    var z=0;
    var io=0;
    var ios=0;
    for (var i = 0; i < cars.length; i++) {
        ios=ios+1;
        j=j+1;
        var rName = "r" + cars[i];
        var rNameStr;
        if (cars[i]==-1) {
            z=0;
            num=i;
            i=i+1;
            for (i=i;cars[i]!=-2; i++){
                var rName = "rr" + cars[i];
                var cc=document.getElementsByName(rName);

                if (cc[0].checked == true) {
                z=z+1;
                }

            }
            if (z==0){
                    io=io+1;
                    f=f+String(ios)+","
            }
        }
        else {
            rNameStr = "document.myform." + String(rName) + ".value";
            rNameStr = eval(rNameStr);

            if (!rNameStr) {
                io=io+1;
                f=f+String(ios)+","
            }
        }
    }
    if (io>0){
            alert(f + "题还未选择");
                return false;
    }
}

</script>
<div id="container">
　<table  height="100%" align="center">
　　<tr>
　　<td>
　　<div align="center">

   <div class="container">
   <div class="row" >
      <div class="col-xs-10 col-sm-6 col-md-8  col-md-offset-2 "

         box-shadow: inset 0px 0px 1px #234, inset 0px 0px 0px #244;">
<ul>
<p class="lead">试卷名称：{{ f.questionaire_text }}</p>
<p >开始时间：{{ t1}}</p>
<p >结束时间：{{ t2}}</p>
<p class="text-left"  >{{ f.questionaire_ad}}我们会在活动结束后进行抽奖，抽奖结果公布地址为<a href="drawn">&lt;抽奖结果&gt;</a>
</p>
</ul>
      </div></div></div>
{% if latest_question_list %}
    <ul>
<form class="bs-example bs-example-form" name="myform" action="{% url 'polls:vote'%}" onsubmit="return checkMyform();" method="post">
    {% csrf_token %}
<ol>
        {% for question in latest_question_list %}


   <div class="row" >
      <div class="col-xs-10 col-sm-6 col-md-8  col-md-offset-2 "

         box-shadow: inset 0px 0px 1px #000, inset 0px 0px 0px #000;">
　   <table class="table table-striped">
　　      <tr>
　　      <td>
            <li><a  >{{ question.question_text }}</a></li>
            {% for choice in question.choice_set.all %}
                {% if question.sf %}
            <input type="checkbox"  name=rr{{ choice.id }} id="choice  {{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice {{ forloop.counter }}" required>{{ choice.choice_text }}</label><br />
            {% else %}
            <input type="radio"  name=r{{ question.id }} id="choice  {{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice {{ forloop.counter }}" required>{{ choice.choice_text }}</label><br />
                    <input class="sr-only" type="number" name="wjid" value="{{ question.questionaire.id }}" />
                {% endif %}
            {% endfor %}
            </td>
　　      </tr>
　　  </table>
             </div></div>
        {% endfor %}
</ol>
 <div class="row">
   <div class="container">
   <div class="row" >
      <div class="col-xs-20 col-sm-10 col-md-8 col-md-offset-2 "

         box-shadow: inset 0px 0px 1px #234, inset 0px 0px 0px #244;">
 <table class="table"  >
　　      <tr>
　　      <td>
     <p class="text-left"  >请输入您的姓名，邮箱以及手机号，以便我们在您中奖的时候联系您</p>
    <div class="form-group" style="padding: 10px 0px 50px;">
        <div class="col-xs-6">
        <label for="exampleInputEmail1">姓名</label>
        <input type="text" class="form-control" name="firstname" placeholder="请输入您的姓名" required="required">
    </div></div>
   <div class="form-group" style="padding: 10px 0px 50px;">
        <div class="col-xs-6">
        <label for="exampleInputEmail1">邮箱</label>
        <input type="email" class="form-control" name="email" placeholder="请输入您的邮箱" required="required">
    </div></div>
       <div class="form-group" style="padding: 10px 0px 10px;">
        <div class="col-xs-6">
        <label for="exampleInputEmail1">电话号码</label>
        <input class="form-control" id="private_phone" name="phone_number" pattern="(\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$" placeholder="请输入您的电话号码" required="required" type="text" />
    </div></div>
     <button type="submit" class="btn btn-default" onsubmit="checkMyform();">提交</button>
      </td>
　　      </tr>
　　  </table>
       </div></div></div>
</form>
    </ul>
    </div>
　　</td>
　　</tr>
　　</table>

{% else %}
    <p>No polls are available.</p>
{% endif %}